name: Release
on:
  push:
    # tags:
    #   - 'v*'

jobs:
  check: 
    runs-on: ubuntu-latest
    outputs: 
      branch: steps.tag.outputs.current_branch 
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get branch name
        id: tag
        uses: tj-actions/branch-names@v6

      - name: Echo
        run: echo '${{ steps.tag.outputs.current_branch }}'
      

  release:
    needs: 
      - check
    if: ${{ needs.check.outputs.branch == 'dev' }}
    strategy:
      fail-fast: true
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:

     
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
            ${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile


      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Install app dependencies
        run: pnpm install

      - name: Build web
        run: pnpm build

      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');

   

      - name: Build the app
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: test 23 # tauri-action replaces \_\_VERSION\_\_ with the app version
          releaseName: test 23
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false